# Generated by Django 2.2.3 on 2019-09-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, help_text='YYYY-MM-D', null=True)),
                ('date_of_death', models.DateField(blank=True, help_text='YYYY-MM-D', null=True, verbose_name='died')),
            ],
        ),
    ]
